# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 698)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_author = QtGui.QLabel(self.centralwidget)
        self.label_author.setObjectName(_fromUtf8("label_author"))
        self.horizontalLayout_2.addWidget(self.label_author)
        self.content_author = QtGui.QLineEdit(self.centralwidget)
        self.content_author.setText(_fromUtf8(""))
        self.content_author.setObjectName(_fromUtf8("content_author"))
        self.horizontalLayout_2.addWidget(self.content_author)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.author_submit = QtGui.QPushButton(self.centralwidget)
        self.author_submit.setObjectName(_fromUtf8("author_submit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.author_submit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_title = QtGui.QLabel(self.centralwidget)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.horizontalLayout_3.addWidget(self.label_title)
        self.content_title = QtGui.QLineEdit(self.centralwidget)
        self.content_title.setText(_fromUtf8(""))
        self.content_title.setObjectName(_fromUtf8("content_title"))
        self.horizontalLayout_3.addWidget(self.content_title)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.title_submit = QtGui.QPushButton(self.centralwidget)
        self.title_submit.setObjectName(_fromUtf8("title_submit"))
        self.horizontalLayout_6.addWidget(self.title_submit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_3.addWidget(self.listWidget)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.progressBtn = QtGui.QPushButton(self.centralwidget)
        self.progressBtn.setObjectName(_fromUtf8("progressBtn"))
        self.verticalLayout_3.addWidget(self.progressBtn)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setProperty("value", 50)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.verticalLayout_3.addWidget(self.horizontalScrollBar)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.nlcd = QtGui.QLCDNumber(self.centralwidget)
        self.nlcd.setObjectName(_fromUtf8("nlcd"))
        self.verticalLayout.addWidget(self.nlcd)
        self.hsld = QtGui.QSlider(self.centralwidget)
        self.hsld.setTracking(True)
        self.hsld.setOrientation(QtCore.Qt.Horizontal)
        self.hsld.setObjectName(_fromUtf8("hsld"))
        self.verticalLayout.addWidget(self.hsld)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnBrowse = QtGui.QPushButton(self.centralwidget)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout_5.addWidget(self.btnBrowse)
        self.close = QtGui.QPushButton(self.centralwidget)
        self.close.setObjectName(_fromUtf8("close"))
        self.horizontalLayout_5.addWidget(self.close)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.blue = QtGui.QPushButton(self.centralwidget)
        self.blue.setObjectName(_fromUtf8("blue"))
        self.verticalLayout_2.addWidget(self.blue)
        self.red = QtGui.QPushButton(self.centralwidget)
        self.red.setObjectName(_fromUtf8("red"))
        self.verticalLayout_2.addWidget(self.red)
        self.green = QtGui.QPushButton(self.centralwidget)
        self.green.setObjectName(_fromUtf8("green"))
        self.verticalLayout_2.addWidget(self.green)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.square = QtGui.QFrame(self.centralwidget)
        self.square.setFrameShape(QtGui.QFrame.StyledPanel)
        self.square.setFrameShadow(QtGui.QFrame.Raised)
        self.square.setObjectName(_fromUtf8("square"))
        self.kpixmapregionselectorwidget = KPixmapRegionSelectorWidget(self.square)
        self.kpixmapregionselectorwidget.setGeometry(QtCore.QRect(110, 20, 27, 35))
        self.kpixmapregionselectorwidget.setObjectName(_fromUtf8("kpixmapregionselectorwidget"))
        self.horizontalLayout_7.addWidget(self.square)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.splitter)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.splitter)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.verticalLayout_4.addWidget(self.splitter)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_author.setText(_translate("MainWindow", "Author: ", None))
        self.author_submit.setText(_translate("MainWindow", "submit", None))
        self.label_title.setText(_translate("MainWindow", "Title: ", None))
        self.title_submit.setText(_translate("MainWindow", "submit", None))
        self.progressBtn.setText(_translate("MainWindow", "start", None))
        self.btnBrowse.setText(_translate("MainWindow", "Pick a folder", None))
        self.close.setText(_translate("MainWindow", "Close", None))
        self.checkBox.setText(_translate("MainWindow", "CheckBox", None))
        self.blue.setText(_translate("MainWindow", "blue", None))
        self.red.setText(_translate("MainWindow", "red", None))
        self.green.setText(_translate("MainWindow", "green", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

from PyKDE4.kdeui import KPixmapRegionSelectorWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

